doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        logging: false
        profiling: false
        driver: pdo_pgsql
        charset: UTF8
        server_version: 14.2
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci
        url: '%app.db.dsn%'
        use_savepoints: true # TODO: remove after update to DBAL v.4 https://github.com/dmaicher/doctrine-test-bundle
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    enable_lazy_ghost_objects: true # TODO: what is it?
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Instrument:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/Instrument'
        prefix: 'App\Domain\Instrument\Model'
        alias: ~
      Trader:
        type: xml
        is_bundle: false
        dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/Trader'
        prefix: 'App\Domain\Trader\Model'
        alias: ~
