services:
  app.console.instrument.share.import.importer:
    class: App\Console\Instrument\Share\Import\Importer
    arguments:
      - '@app.infrastructure.tinkoff_api.clients_factory'
      - '@app.domain.instrument.builder.share_builder'
      - '@app.domain.instrument.repository.share_repository_interface'
    calls:
      - setLogger: ['@logger']
