services:
  app.console.trader.trader.import.command:
    class: App\Console\Trader\Trader\Import\Command
    arguments:
      - '@app.console.trader.trader.import.importer'
      - '%app.moex.trader.file_name%'
    calls:
      - setLogger: ['@logger']
    tags:
      - { name: console.command, command: 'app:trader:trader:import', description: 'Import all traders by year' }
