services:
  app.console.trader.trader.import.importer:
    class: App\Console\Trader\Trader\Import\Importer
    arguments:
      - '@app.console.trader.trader.import.fetcher'
      - '@app.domain.trader.service.trader_builder'
      - '@app.infrastructure.doctrine.bulk_persister'
