services:
  app.console.trader.trader.import.importer:
    class: App\Console\Trader\Trader\Import\Importer
    arguments:
      - '@app.console.trader.trader.import.fetcher'
      - '@app.domain.trader.factory.trader_factory'
      - '@app.domain.trader.service.trader_saver'
    calls:
      - setLogger: ['@logger']
