services:
  app.domain.trader.factory.trader_factory:
    class: App\Domain\Trader\Factory\TraderFactory
    arguments:
      - '@app.domain.common.service.id_service'

  app.domain.trader.service.trader_builder:
    class: App\Domain\Trader\Service\TraderBuilder
    arguments:
      - '@app.domain.trader.repository.trader_repository_interface'
      - '@app.domain.trader.factory.trader_factory'
