services:
  app.domain.trader.factory.trader_factory:
    class: App\Domain\Trader\Factory\TraderFactory
    arguments:
      - '@app.domain.common.service.id_service'

  app.domain.trader.service.trader_saver:
    class: App\Domain\Trader\Service\TraderSaver
    arguments:
      - '@app.domain.instrument.repository.trader_repository_interface'
