services:
  # Instrument
  app.domain.instrument.repository.share_repository_interface:
    alias: app.infrastructure.doctrine.repository.share_repository

  # Trader
  app.domain.trader.repository.trader_repository_interface:
    alias: app.infrastructure.doctrine.repository.trader_repository

  app.domain.trader.repository.trade_repository_interface:
    alias: app.infrastructure.doctrine.repository.trade_repository

  app.domain.trader.repository.broker_repository_interface:
    alias: app.infrastructure.doctrine.repository.broker_repository

  app.domain.trader.repository.result_repository_interface:
    alias: app.infrastructure.doctrine.repository.result_repository

  # Marketdata
  app.domain.marketdata.repository.candle_repository_interface:
    alias: app.infrastructure.doctrine.repository.candle_repository
