services:
  app.console.trader.trade.import.fetcher:
    class: App\Infrastructure\Fetcher\BaseFetcher
    arguments:
      - '@app.console.trader.trade.import.fetcher.http_client'
      - '@app.console.trader.trade.import.fetcher.response_transformer'
    calls:
      - setLogger: ['@logger']

  app.console.trader.trade.import.fetcher.http_client:
    class: App\Infrastructure\Fetcher\HttpClient\HttpClient
    arguments:
      - '@app.infrastructure.http_client'
      - '@app.console.trader.trade.import.fetcher.request_builder'

  app.console.trader.trade.import.fetcher.request_builder:
    class: App\Console\Trader\Trade\Import\Fetcher\RequestBuilder
    arguments:
      - 'GET'
      - '%app.moex.base_url%/:year/all'

  app.console.trader.trade.import.fetcher.response_transformer:
    class: App\Console\Trader\Trade\Import\Fetcher\ResponseTransformer
    arguments:
      - '@app.infrastructure.common.file.file_helper'
      - '%kernel.project_dir%/var/trade'
