services:
  app.domain.trader.factory.broker_factory:
    class: App\Domain\Trader\Factory\BrokerFactory
    arguments:
      - '@app.domain.common.service.id_service'

  app.domain.trader.service.broker_saver:
    class: App\Domain\Trader\Service\BrokerSaver
    arguments:
      - '@app.domain.trader.repository.broker_repository_interface'
