services:
  app.domain.instrument.factory.share_factory:
    class: App\Domain\Instrument\Factory\ShareFactory
    arguments:
      - '@app.domain.common.service.id_service'

  app.domain.instrument.service.share_saver:
    class: App\Domain\Instrument\Service\ShareSaver
    arguments:
      - '@app.domain.instrument.repository.share_repository_interface'
