services:
  app.domain.instrument.factory.share_factory:
    class: App\Domain\Instrument\Factory\ShareFactory
    arguments:
      - '@app.domain.common.service.id_service'

  app.domain.instrument.builder.share_builder:
    class: App\Domain\Instrument\Builder\ShareBuilder
    arguments:
      - '@app.domain.instrument.repository.share_repository_interface'
      - '@app.domain.instrument.factory.share_factory'
