services:
  # Instrument
  app.infrastructure.doctrine.repository.share_repository:
    class: App\Infrastructure\Doctrine\Repository\ShareRepository
    arguments:
      - '@doctrine'
      - 'App\Domain\Instrument\Model\Share'
    tags: [ 'doctrine.repository_service' ]

  # Trader
  app.infrastructure.doctrine.repository.trader_repository:
    class: App\Infrastructure\Doctrine\Repository\TraderRepository
    arguments:
      - '@doctrine'
      - 'App\Domain\Trader\Model\Trader'
    tags: [ 'doctrine.repository_service' ]

  app.infrastructure.doctrine.repository.broker_repository:
    class: App\Infrastructure\Doctrine\Repository\BrokerRepository
    arguments:
      - '@doctrine'
      - 'App\Domain\Trader\Model\Broker'
    tags: [ 'doctrine.repository_service' ]
