services:
  app.infrastructure.http_client:
    class: GuzzleHttp\Client
    arguments:
      - timeout: '%env(HTTP_TRANSPORT_TIMEOUT)%'
        connect_timeout: '%env(HTTP_TRANSPORT_CONNECT_TIMEOUT)%'
        verify: '%env(bool:HTTP_TRANSPORT_SSL_VERIFY)%'
        headers:
          User-Agent: '%env(HTTP_TRANSPORT_USER_AGENT)%'

  app.infrastructure.tinkoff_api.clients_factory:
    class: Metaseller\TinkoffInvestApi2\TinkoffClientsFactory
    factory: [null, 'create']
    arguments:
      $api_token: '%app.tinkoff.api.token%'

  app.infrastructure.doctrine.bulk_persister:
    class: App\Infrastructure\Doctrine\BulkPersister
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%app.doctrine.batch_size.default%'

  app.infrastructure.common.file.file_helper:
    class: App\Infrastructure\Common\File\FileHelper
