services:
  app.console.share.import_from_api_command:
    class: App\Console\Share\Import\Command
    arguments:
      - '@app.console.share.import.importer'
    calls:
      - setLogger: ['@logger']
    tags:
      - { name: console.command, command: 'app:share:import', description: 'Получение списка всех акций' }
