services:
  app.console.share.import.importer:
    class: App\Console\Share\Import\Importer
    arguments:
      - '@app.infrastructure.tinkoff_api.clients_factory'
      - '@app.domain.instrument.service.share_saver'
    calls:
      - setLogger: ['@logger']
